MTG_DB_URL = 'http://api.mtgdb.info'
CARDS_PATH = 'cards'
SETS_PATH = 'sets'
RANDOM_CARD_PATH = 'random'
REG_IMAGE_URL = 'http://api.mtgdb.info/content/card_images'
HI_RES_IMAGE_URL = 'http://api.mtgdb.info/content/hi_res_card_images'
